# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm install --ignore-scripts

# Copy source and build
COPY tsconfig.json ./
COPY src ./src
RUN npm run build

# Default environment variables
ENV TRANSPORT_TYPE=stdio
ENV PORT=3000
ENV LOG_LEVEL=info

# Expose port for SSE transport
EXPOSE 3000

# Start the MCP server
CMD ["node", "dist/index.js"]
